### PR TITLE
Fix for issue raised on the rtree

### PR DESCRIPTION
**Pull request by seanmalter**
## Description
This pull request is to fix the issue found and noted in #4. To resolve the issue the  `overlap_rectangle` function will now consider a rectangles with equal sides as overlapping.

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for this patch @seanmalter 👍. just out of curiosity, what version of Node.js did you use to run the tests?

i saw errors yesterday, even on 6.x.

**Comment by seanmalter** [comment]
@jgravois I'm using 8.12.0. I did have to modify the test cases so that geojson that are on the edges of the rectangle are considered. I'm a little hesitant of these changes and actually think that we might want to make a new `Rectangle.inclusive_overlap_rectangle` that has the changes needed for `_remove_subtree` so we don't lose any functionality and do not alter the current `.within` workflow. Any thoughts @jgravois ?

**Comment by seanmalter** [comment]
@jgravois added a new function `Rectangle.inclusive_overlap_rectangle` and now passes all the test cases without modifying the current `.within` workflow of the geostore

**Comment by jgravois** [comment]
sorry, but i've encountering the same [High Sierra/PhantomJS](https://github.com/karma-runner/karma-phantomjs-launcher/issues/138) problems that resulted in the test harness updates below.

https://github.com/Esri/terraformer-arcgis-parser/pull/52
https://github.com/Esri/terraformer-wkt-parser/pull/34

**Comment by seanmalter** [comment]
tested this further and might still have some issues with a larger set added to the geostore, need to investigate. Closing this for now.

**Comment by seanmalter** [comment]
Is anyone tracking this repo? I had a PR open but found there were issues with @jgravois suggested fix. I dug through the code and wasn't able to pin down the issue.

**Comment by vchan5** [comment]
I am also experiencing this issue. Is there a solution or workaround for now?

**Comment by jgravois** [comment]
> Is anyone tracking this repo?

do you mean someone other than me? likely not.

see https://github.com/Esri/terraformer/issues/268 for more info.

**Pull request closed without merging**
